### ISSUE TITLE
即使把账号删除还是会每日收到自动签到登陆信息过期提醒

### ISSUE THREAD

**Issue by fanweiya** [imebeh/V2EX-daily-mission#3]
试用过这个Demo:https://v2ex-daily.appspot.com
然后我把V2EX账号删除啦！可是Gmail邮箱还是会每日收到登陆信息过期邮件,

>V2EX每日自动签到登录信息过期，需要重新登录。
>Username: ****
>http://v2ex-daily.appspot.com

作者可否解决一下

**Comment by imebeh** [comment]
之前提醒邮件的应用地址是直接写的我自己的 GAE 应用地址，所以有其他人架设的 GAE 应用的提醒邮件也会导航到我的这里，其实需要在之前登录的 GAE 应用里面设置；可以在提醒邮件的发件人找到那个应用的 id，如发件人是 noreply@**appid**.appspotmail.com，访问 https://**appid**.appspot.com 设置即可。

这个问题在 8c75ddb22465f479c5542d31b01c184dd26ff2b2 中已修复

PS1：签到失败只会发送一次提醒邮件 9c3080ff1dff8a224030c21e55c41af63173ae90
PS2：V2EX 改了登录表单 c4bb2acc510b23fc22834c54694d64e146eb7fd3
