### ISSUE TITLE
老大，能不能写个小木虫的自动签到领金币

### ISSUE THREAD

**Issue by xinyue** [imebeh/V2EX-daily-mission#4]
这个 V2EX 的自动签到太好用了，偶尔需要在小木虫 (http://muchong.com/bbs/index.php) 下个教程什么的，但是每天手动签到太麻烦了，所以能不能也写一个类似 V2EX-daily-mission 的放到 GAE 上，每天自动运行？

**Comment by imebeh** [comment]
@xinyue 这不是这个程序的 bug 哦。
